# Generated by Django 4.2.5 on 2023-09-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('age', models.PositiveSmallIntegerField(default=25)),
                ('email', models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True)),
                ('phone', models.CharField(max_length=19)),
                ('about', models.TextField(blank=True, default='Your about only', null=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('year', models.DateField(blank=True, null=True)),
                ('ganre', models.CharField(choices=[('rap', 'Rap'), ('jazz', 'Jazz'), ('hiphop', 'HipHop'), ('national', 'national'), ('rock', 'Rock')], max_length=15)),
                ('artist', models.ManyToManyField(blank=True, null=True, to='app1.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SongRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.artist')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.song')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('album_img', models.FileField(blank=True, null=True, upload_to='media/album_image')),
                ('year', models.DateTimeField(default=2023)),
                ('album_about', models.TextField(blank=True, default='About your album', null=True)),
                ('artist', models.ManyToManyField(blank=True, null=True, to='app1.artist')),
                ('song', models.ManyToManyField(blank=True, null=True, to='app1.song')),
            ],
        ),
    ]
